development:
  adapter: postgresql
  database: db/tallerarmero-development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/tallerarmero-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/tallerarmero-production
  pool: 5
  timeout: 5000
